language: node_js
sudo: false
node_js:
  - "8"
cache: yarn
before_script: yarn global add codecov
script:
  - yarn lint
  - yarn test --coverage --maxWorkers=4
  - yarn build
after_success:
  - codecov
  - .travis/after_success.sh
env:
    global:
    - REPO="git@github.com:RedHatInsights/cost-management-build"
    - REPO_DIR="cost-management-build"
    - BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}