language: node_js
sudo: false
node_js:
  - "8"
cache: yarn
script:
  - yarn build
after_success:
  - curl -sSL https://raw.githubusercontent.com/RedHatInsights/insights-frontend-builder-common/master/src/bootstrap.sh | bash -s
env:
    global:
    - REPO="git@github.com:RedHatInsights/cost-management-build"
    - REPO_DIR="cost-management-build"
    - BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
    - APP_BUILD_DIR="public"
