name: github-bot

on:
  schedule:
  - cron: "0 * * * *"

jobs:
  is-status-review:
    runs-on: ubuntu-latest
    steps:
    - name: Code review status
      uses: actions/github-script@0.4.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const re = /address #\d+/g;
          const body = context.payload.pull_request.body
          const matches = re.exec(body)

          if (matches && matches.length) {
            issue_number = matches[0].split('#')[1]
            github.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
            }).then(resp => {
              resp.data.map(label => label.name)
                .filter(label => label.startsWith('status/') && label !== 'status/code-review')
                .forEach(label => {
                  github.issues.removeLabel({
                    issue_number: issue_number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    name: label,
                  })
                })
            })
            github.issues.addLabels({
              issue_number: issue_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['status/code-review']
            })
          }
